### ISSUE TITLE
Provide binaries through github releases

### ISSUE THREAD

**Issue by schell** [franckverrot/terraform-provider-stripe#10]
First off - thank you! 

Having binary releases would be really nice for those of us that are not Go developers and would like to use this provider with our current CICD processes. You can see an example of another community provider that does this - [auth0](https://github.com/yieldr/terraform-provider-auth0).

**Comment by franckverrot** [comment]
Thanks!

Oh yes indeed.  Thanks for reporting this.  I’ll see how I can automate this, as I had to do it manually for Trek and that didn’t feel sustainable.  Also, thanks for pointing to that other project, it will make the investigations simpler :-)

Cheers!

**Comment by franckverrot** [comment]
Sorry it took a long time to get to release.  I'm trying out `ghr` and it's fighting me a little, but I got to release version `0.0.1` (should have been 1.0 I guess, but I'd like to fix a couple things before 1.0.  Please re-open if it doesn't work!  Thanks!

**Comment by schell** [comment]
Thanks for the work! :)
