### ISSUE TITLE
possibility to use terraform import ?

### ISSUE THREAD

**Issue by allanlegalstart** [franckverrot/terraform-provider-stripe#11]
It's not written explicitly in the documentation, but can i use "terraform import" with this plugin ?

**Comment by franckverrot** [comment]
@allanlegalstart Thanks for asking, I indeed forgot to show how to import an existing resource.

Please take a look at the README (updated here https://github.com/franckverrot/terraform-provider-stripe/commit/267f15b8715ed705d4d234cb98e8c69749e3c4ad), and tell me if it's enough info.  Thanks!

**Comment by allanlegalstart** [comment]
awesome thanks, that's enough for me :)
