### ISSUE TITLE
compilation error: github.com/hashicorp/go-getter checksum mismatch

### ISSUE THREAD

**Issue by allanlegalstart** [franckverrot/terraform-provider-stripe#13]
```
go: downloading github.com/hashicorp/hcl v0.0.0-20170504190234-a4b07c25de5f                                                                                                                                                                  
go: verifying github.com/hashicorp/go-getter@v0.0.0-20180327010114-90bb99a48d86: checksum mismatch                                                                                                                                           
        downloaded: h1:mv3oKLM8sTaxmU/PrT39T35HRnUfchK+vtzXw6Ci9lY=                                                                                                                                                                          
        go.sum:     h1:hLYM35twiyKH44g36g+GFYODcrZQetEAY4+zrJtGea0=
```

**Comment by franckverrot** [comment]
I can't reproduce this locally.  What command are you launching?

**Comment by allanlegalstart** [comment]
simply `make install` I have a fresh install of with the latest version normally 

for the moment i've worked around by using your binary release (I got lucky that you had release it just a little before i started using your plugin :P )

**Comment by franckverrot** [comment]
What version of go are you using?

Here's the output on my machines:

```
λ go version
go version go1.12.5 darwin/amd64
λ make
go get ./...
go build -o terraform-provider-stripe

λ echo $?
0
```

**Comment by allanlegalstart** [comment]
sorry my dev environment are all in docker containers, and i already destroyed the one where i manually installed go and tried to compile the plugin, and now the Dockerfile pre-download your binary release, so I don't think i will find the time to investigate more, in a way now that I have the binary release and if for you it works, maybe it's not relevant anymore and we can close this ticket ?

**Comment by franckverrot** [comment]
Thanks for the feedback.  Let’s close and reopen if necessary!  Thanks again!
