### ISSUE TITLE
Resource : subscription

### ISSUE THREAD

**Issue by mytototo** [franckverrot/terraform-provider-stripe#15]
Hi there,

First of all I would like to thank you for this provider. It's really useful.

How is it possible to add a customer and a subscription (a relation between a customer and a product) ? This is the only thing missing for me before starting using it.

Thanks.

**Comment by clintonb-stripe** [comment]
@mytototo this provider is intended to create the static parts of a subscription—the products and plans—that don't change very frequently. Individual subscription data does not apply here since they change on a frequent basis (e.g. monthly). Ideally, this data should be stored in your database.

**Comment by mytototo** [comment]
I understand, thanks for your feedback.
