### ISSUE TITLE
Upgrade terraform to v0.12

### ISSUE THREAD

**Issue by bradrydzewski** [franckverrot/terraform-provider-stripe#17]
hey there, really excited to find this terraform plugin. I am getting the below error. I am guessing that this is because I upgraded to terraform 0.12 and this plugins uses client version 0.11.13.

```
Error: Failed to instantiate provider "stripe" to obtain schema:
Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

I was wondering if you have any plans to upgrade to 0.12?

**Comment by bradrydzewski** [comment]
I updated the terraform package version and it compiled and ran without issue, although I only tested a small subset of functionality.

```diff
--- a/go.mod
+++ b/go.mod
@@ -3,6 +3,6 @@ module github.com/franckverrot/terraform-provider-stripe
 go 1.12
 
 require (
-       github.com/hashicorp/terraform v0.11.13
+       github.com/hashicorp/terraform v0.12.5
        github.com/stripe/stripe-go v60.12.2+incompatible
 )
```

The changes to the vendor directory were significant.  I am not sure if you prefer to generate the vendor directory yourself (for integrity reasons) or if you would like me to send a pull request. At the moment I'm fine using my custom build, but would be happy to help where I can.

**Comment by franckverrot** [comment]
The release progress wasn’t functional so I’m not auto-releasing, which means I’ll have to build the binaries and release from my machine(s).  If you’d like to send a PR I’ll review, and eventually compare with what I got here.  I’ll get to this later this week or this week-end, probably ™️  😅   Thanks for filing this btw, I haven’t switched to v12 yet.

**Comment by bradrydzewski** [comment]
let me know if you would like help automating your releases. I run cloud.drone.io, a free CI service for open source projects, so I have some experience automating releases :)

**Comment by franckverrot** [comment]
Ahah thanks.  Yeah I ran into some issues with github.com/tcnksm/ghr and never fixed them, things should be fine but I had 0 time to investigate 🤷‍♂

**Comment by franckverrot** [comment]
Ok done, just release v1.0.0.  Please tell me if things are OK for you now!
