### ISSUE TITLE
Different behavior when using release and building from source

### ISSUE THREAD

**Issue by florisvdg** [franckverrot/terraform-provider-stripe#20]
When I install a 0.12 compatible GitHub release of this provider (i.e. `1.0.0` and `1.1.0`) and `terraform validate` my 0.12 Terraform code, I get an error that the plugin is outdated:

```
Error: Failed to instantiate provider "stripe" to obtain schema: 
Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

However, when I `make install` the corresponding commit, it works just fine.

**Comment by franckverrot** [comment]
How do you install the release currently?

**Comment by franckverrot** [comment]
Ok I think I released the wrong one, sorry about that.  Juggling between TF versions ain't fun 😭 

Here's the new version, works on my machine ™️ 😂 : https://github.com/franckverrot/terraform-provider-stripe/releases/tag/v1.2.0
