### ISSUE TITLE
Please consider retagging with Go Modulex prefix

### ISSUE THREAD

**Issue by SamWhited** [franckverrot/terraform-provider-stripe#29]
Hi, I've noticed that recent tags to this project don't have the "v" prefix, ie. the tag is `1.4.0` unlike 1.2.0 which was tagged `v1.2.0`. Please consider adding tags with the v prefix, both so that they can be recognized by Go Modules, and also so that package maintainers building this library have a consistent way to reference releases. Thanks for your time and consideration!

**Comment by franckverrot** [comment]
Oh snap, thanks for reporting this... I've been very inconsistent here 🤦 

I'm releasing `v1.5.0` right now, do you want me to also release `v1.4.0` or we're good? 

Sorry if this has been painful, I'll do better from now on!

**Comment by SamWhited** [comment]
If you could add a tag with v1.4.0 that would be very convenient if possible; thanks. Something like: `git tag v1.4.0 1.4.0` should do the trick. If it would cause other problems or just clutter the repo though, I completely understand. Thanks for your help.

**Comment by franckverrot** [comment]
Haha no worries, done.  This repo is everything but cluttered 😅 

Thanks for the feedback, really appreciated!  Hope it's good now.
