### ISSUE TITLE
Publish provider for use in Terraform 0.13

### ISSUE THREAD

**Issue by aicarmic** [franckverrot/terraform-provider-stripe#30]
👋 Hi, I'm on the Terraform Providers team at HashiCorp. With the release of the Terraform 0.13 beta, users can now download and install community providers from the registry. We are inviting provider authors (especially those for popular community providers) to publish their providers in a closed beta.

To get invited to the closed beta, please email terraform-registry-beta@hashicorp.com. We need:

- A list of GitHub usernames to add to the beta (you and any team members who will publish)
- List of provider repositories you plan to publish
- A GPG public key in ASCII-armor format, which you will be using to sign your provider releases

You can use one key for all of your providers, or separate keys if you prefer. If you are publishing from an organization, this key or keys will be associated with that namespace. Once in the beta, you can manage personal keys in the UI as well.

**Comment by franckverrot** [comment]
Amazing!  I'll reach out soon, thanks!

**Comment by razor-x** [comment]
Hi @franckverrot it looks like Terraform 0.13 was released and the registry is open: https://registry.terraform.io/search/providers?q=stripe

Any chance you can get the latest version in there? I am looking to update soon. Best.

**Comment by andreyvital** [comment]
Also needing it.

**Comment by franckverrot** [comment]
Hey folks.  I was planning on doing it last week but had to escape bad air quality and fires here in California.  I’ll do this ASAP for sure, thanks and sorry for waiting.

**Comment by franckverrot** [comment]
Back home, safe and sound, thanks for the hearts, really appreciated!

[Here's the release.](https://registry.terraform.io/providers/franckverrot/stripe/latest)  Have a great weekend!

**Comment by andreyvital** [comment]
Thanks Franck—now we're back in business with Stripe on Terraform.

Have a good weekend too!
