### ISSUE TITLE
Support for creating API keys

### ISSUE THREAD

**Issue by ajbouh** [franckverrot/terraform-provider-stripe#36]
I'd like to dynamically provision Stripe API keys for my app that are easy to revoke.

The simplest way to do this seems to be using a master API key with this provider and then using this provider to create per-app API keys.

I see that there's support for client secrets for the Stripe Connect API. Is there a technical reason that API keys are not supported?

**Comment by franckverrot** [comment]
I can't seem to find anything in the API that talks about this.  I'd love to support this though, do you mind sharing where you found this?  Thanks!

**Comment by ajbouh** [comment]
Sorry, I haven't found a way to do this for Stripe API keys in general.

My comment was intended to be more aspirational than it came across.

I was try to ask if you knew why it was so hard to do this kind of thing *programmatically*.

**Comment by franckverrot** [comment]
Oh I see, I agree it’d be great (I’d even create a Vault plugin for this haha).  So no I don’t think it’s hard, it’s just not supported by the API :-)
