### ISSUE TITLE
Tiers on stripe_price?

### ISSUE THREAD

**Issue by glebpom** [franckverrot/terraform-provider-stripe#37]
It looks like tiers are supported only on a stripe_plan resource. Stripe UI has support for graduated tiers on a separate price object. Is it possible to provide tiers on a per-price basis?

**Comment by franckverrot** [comment]
Should be good to go, please try https://github.com/franckverrot/terraform-provider-stripe/releases/tag/v1.7.0

**Comment by glebpom** [comment]
Thanks!
