### ISSUE TITLE
How come stripe doesn't support this project?

### ISSUE THREAD

**Issue by Josh-a-e** [franckverrot/terraform-provider-stripe#41]
Feels particularly weird given how they have [published terraform providers for other things](https://github.com/stripe/terraform-provider-confidant).

@stripe

**Comment by franckverrot** [comment]
I know at least one person working there who contributed here, and [they worked with their team to fix some APIs](https://github.com/stripe/stripe-go/issues/788) that wasn't behaving properly.  It's not official endorsement, but I know it's a project they know about.

I created this provider to solve my own problems and eventually made it open source and published it, so it's not as weird as it sounds I think: someone (in this case me) had a need for this and made something happen :-).  Do you mind expanding on what would be your expectation with regards to Stripe supporting it?

Thanks for reaching out, Joshua!
