### ISSUE TITLE
Add build for darwin/arm64

### ISSUE THREAD

**Issue by analytically** [franckverrot/terraform-provider-stripe#55]

**Comment by herissondev** [comment]
Have you found a fix to that problem ? I'm having trouble using the provider with M1 mac

**Comment by analytically** [comment]
@franckverrot

**Comment by r1kaj** [comment]
The provider compiles just fine on my m1 machine and just needs a release for arm.

I'm currently using rosetta and terraform (amd64) as a workaround. 
Simply get the amd64 executable of terraform and run it like this:
```
arch -x86_64 ./terraform_x64 init
```

**Comment by franckverrot** [comment]
I’ll cut a release soon.  I don’t have an M1, pretty expensive beasts… glad you found a workaround though

**Comment by stefano-tilt** [comment]
hey @franckverrot ,

are you planning to merge this fix soon?

Thanks

**Comment by algoflows** [comment]
Dear maintainer @franckverrot , 

If the darwin-arm64 fix gets merged, I'll buy you a coffee.

Promise :)

**Comment by talesporto** [comment]
Hey @franckverrot ,

Please, can you have a look on this? :) 
There is a coffee in the game here. ☕

**Comment by algoflows** [comment]
There's two coffees in the game. I've emailed him and tried to contact him via twitter no response so far 😞

**Comment by franckverrot** [comment]
Hey folks.   I did respond to a DM, and I’ll get to this (I’m not working for Stripe, I balance OSS efforts with my real life).  Thanks for the coffees, they just don’t help getting things done faster but I appreciate the thoughts :-)

**Comment by algoflows** [comment]
@franckverrot is there any way we can help? Pretty desperate to have this fixe merged though... Will honor the coffee pledge!

**Comment by talesporto** [comment]
Hi @franckverrot ,

I totally understood. Let me know if there is anything what I can do to help you with it. :)

**Comment by algoflows** [comment]
Giving up... looks like this repo isn't actively being maintained anymore.

**Comment by franckverrot** [comment]
New release is out.  Better yet than coffee, accepting M1/M2 machine donations ;-)
