### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by algoflows** [franckverrot/terraform-provider-stripe#60]
We have PRs with fixes just sitting waiting to be merged for over a month now.

Specifically, there is a PR open which resolves support for arm and M1 Mac support which has been open for quite some time.,

Would be great if the maintainer would take some action and ownership over whats currently awaiting review.

Happy to assist if you need help reviewing PRs and helping keep things current.

**Comment by franckverrot** [comment]
New release it out today.
